name: CI

on:
  push:            # run on any push, any branch
  pull_request:    # and on PRs
  workflow_dispatch:  # and let you run it manually from the Actions tab

jobs:
  ok:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Sanity ping
        run: |
          echo "✅ GitHub Actions is alive."
          uname -a
          python3 --version || true
